# Generated by Django 2.2.4 on 2019-08-14 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='url',
            field=models.CharField(max_length=1000, validators=[django.core.validators.URLValidator()]),
        ),
    ]
