# Generated by Django 2.2.4 on 2019-08-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0002_auto_20190814_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkstatistics',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_stats', to='tds.Link'),
        ),
    ]
