# Generated by Django 2.2.4 on 2019-08-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0003_auto_20190814_1916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uniqueuserstatistics',
            unique_together={('user', 'link')},
        ),
        migrations.CreateModel(
            name='ClickStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('user_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_stats', to='tds.UniqueUserStatistics')),
            ],
        ),
    ]
